import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import ProviderSession from "./_app";
import ContextMusic from "@/context/ContextMusic";
import Sidebar from "./layout/Sidebar";
import Player from "./layout/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <ContextMusic>
        <ProviderSession>
          <body className={inter.className}>
            <div className="flex height-sidebar">
              <Sidebar />
              <div className="border-4 border-purple-900 flex-col flex-grow overflow-hidden">
                {children}
              </div>
            </div>
            <div>
              <Player />
            </div>
          </body>
        </ProviderSession>
      </ContextMusic>
    </html>
  );
}
