import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppProps } from "next/app";
import { SessionProvider } from "next-auth/react";
import ProviderSession from "./_app";
import ContextMusic from "@/context/ContextMusic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
     <ContextMusic>
        <body className={inter.className}>
          <ProviderSession>{children}</ProviderSession>
        </body>
     </ContextMusic>
    </html>
  );
}
